################
### Language ###
################
language: java

jdk:
  - oraclejdk8

#####################
### Notifications ###
#####################
notifications:
  email: false

script:
  - mvn clean test compile package

deploy:
  provider: script
  script: mvn deploy
  on:
    tags: true

