################
### Language ###
################
language: java

jdk:
  - oraclejdk8

#####################
### Notifications ###
#####################
notifications:
  email: false

script:
  - mvn clean test compile

